// Generated by https://quicktype.io

import { Gasto } from "./gasto.interface";

export interface DetalleGastoDTO {
  id: number;
  precio:   number;
  subtotal?: number;
  cantidad: number;
  producto: string;
  gasto: Gasto;
}
