

// Generated by https://quicktype.io

export interface Gasto {
  id:          number;
  descripcion: string;
  fechaGasto:  string;
  tipoGasto:   tipoGasto;
}

export type tipoGasto = 'GASTOS_COMUN' | 'SUPERMERCADO' | 'CASA_COMERCIAL' | 'FERRETERIA' | 'LEÑA' | 'ROPA' | 'VIAJE' | 'OTRO'
